# Generated by Django 3.0.8 on 2021-01-01 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0003_myuser_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myuser',
            name='role',
            field=models.CharField(choices=[('N', 'Normal'), ('A', 'Admin'), ('C', 'Customer Care'), ('T', 'Technician')], default='N', max_length=5),
        ),
    ]
